name: audio_output_manager
description: >-
  A Flutter plugin to manage audio output devices on Android and iOS.
  This plugin allows you to switch between different audio output devices
  such as speakers, headphones, and Bluetooth devices.
version: 1.0.0
homepage: https://github.com/onuragtas/audio_output_manager
repository: https://github.com/onuragtas/audio_output_manager
issue_tracker: https://github.com/onuragtas/audio_output_manager/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: org.resoft.audio_output_manager
        pluginClass: AudioOutputManagerPlugin
      ios:
        pluginClass: AudioOutputManagerPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0