name: audio_output_manager
description: The advanced_audio_manager listens to, gets and modifies audio input/output devices.
version: 1.0.2
homepage: https://github.com/onuragtas/audio_output_manager

environment:
    sdk: '>=3.0.1 <4.0.0'
    flutter: ">=2.5.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    plugin:
        platforms:
            android:
                package: org.resoft.audio_output_manager
                pluginClass: FlutterAudioManagerPlugin
            ios:
                pluginClass: FlutterAudioManagerPlugin
